@echo off
setlocal enabledelayedexpansion

:: 1. Configuration
set "PROJECT_NAME=SSOEngine"
set "BUILD_DIR=build"
set "ASSET_SRC=assets"
set "PACKER_SRC=..\00_BuildTools\sso_packer.cpp"
set "PACKER_EXE=..\00_BuildTools\sso_packer.exe"
set "ICON_RES=resource.rc"

echo ===================================================
echo    SSOEngine v1.0 - Automated Build System
echo ===================================================

:: 1.5 Metadata Wizard
set /p update_meta="Do you want to edit Game Details? [y/n]: "

if /i "%update_meta%"=="y" (
    echo.
    set /p g_name="Enter Game Name: "
    set "g_name=!g_name: =_!"
    set "PROJECT_NAME=!g_name!"
    
    set /p g_desc="Enter Game Description: "
    set /p g_comp="Enter Company Name: "
    set /p g_vers="Enter Version: "

    echo [SSOEngine] Generating %ICON_RES%...
    (
    echo // AUTO-GENERATED BY SSOENGINE BUILD SYSTEM
    echo IDI_ICON1               ICON    DISCARDABLE     "app_icon.ico"
    echo.
    echo 1 VERSIONINFO
    echo  FILEVERSION 1,0,0,0
    echo  PRODUCTVERSION 1,0,0,0
    echo  FILEFLAGSMASK 0x3fL
    echo  FILEFLAGS 0x0L
    echo  FILEOS 0x40004L
    echo  FILETYPE 0x1L
    echo  FILESUBTYPE 0x0L
    echo BEGIN
    echo     BLOCK "StringFileInfo"
    echo     BEGIN
    echo         BLOCK "040904b0"
    echo         BEGIN
    echo             VALUE "CompanyName", "!g_comp!"
    echo             VALUE "FileDescription", "!g_desc!"
    echo             VALUE "FileVersion", "!g_vers!"
    echo             VALUE "InternalName", "!g_name!"
    echo             VALUE "LegalCopyright", "Copyright (C) 2026 !g_comp!"
    echo             VALUE "OriginalFilename", "!g_name!.exe"
    echo             VALUE "ProductName", "!g_name!"
    echo             VALUE "ProductVersion", "!g_vers!"
    echo         END
    echo     END
    echo     BLOCK "VarFileInfo"
    echo     BEGIN
    echo         VALUE "Translation", 0x409, 1200
    echo     END
    echo END
    ) > %ICON_RES%
)

set "OUTPUT_EXE=%BUILD_DIR%\%PROJECT_NAME%.exe"

:: 2. Create Build Directory
if not exist "%BUILD_DIR%" mkdir "%BUILD_DIR%"

:: 3. Asset Packing Phase
if exist "%ASSET_SRC%" (
    echo [SSOEngine] Packing assets...
    pushd ..\00_BuildTools
    if not exist "sso_packer.exe" (
        g++ sso_packer.cpp -o sso_packer.exe -std=c++17
    )
    sso_packer.exe
    popd
    timeout /t 1 >nul 
)

:: 4. Resource Compilation
echo [SSOEngine] Compiling Resources...
windres "%ICON_RES%" -o "%BUILD_DIR%\resource.o"

:: 5. Main Compilation
echo [SSOEngine] Compiling %PROJECT_NAME%...
g++ main.cpp "%BUILD_DIR%\resource.o" -o "%OUTPUT_EXE%" ^
    -I. -I../include -L../lib ^
    -lraylib -lopengl32 -lgdi32 -lwinmm

:: 6. Check Result
if %errorlevel% neq 0 (
    echo.
    echo [ERROR] Build Failed! Check your code, Zak!
    pause
    exit /b %errorlevel%
)

echo.
echo ===================================================
echo [SUCCESS] Build Complete!
echo [LOCATION] %OUTPUT_EXE%
echo [NOTE] Please run the EXE manually from the build folder.
echo ===================================================
pause