@echo off
setlocal enabledelayedexpansion

:: ===================================================
:: SSOEngine v1.0 - Automated Build System
:: (c) 2026 SSOGames Studio
:: ===================================================

:: -------------------------------
:: Configuration
:: -------------------------------
set "PROJECT_NAME=RO-SHADOW"
set "BUILD_DIR=build"
set "ASSET_SRC=assets"
set "ICON_RES=resource.rc"

set "RAYLIB_LIB=..\lib\libraylib.a"

echo ===================================================
echo        SSOEngine v1.0 - Automated Build System
echo ===================================================

:: ===================================================
:: RAYLIB CHECK
:: ===================================================
if not exist "%RAYLIB_LIB%" (

echo.
echo [SSOEngine] Raylib not found. Installing...

if not exist "..\lib" mkdir "..\lib"
if not exist "..\include" mkdir "..\include"

echo [INFO] Downloading Raylib...

powershell -Command "Invoke-WebRequest https://github.com/raysan5/raylib/releases/download/5.0/raylib-5.0_win64_mingw-w64.zip -OutFile raylib.zip"

if not exist "raylib.zip" (
echo [ERROR] Failed to download Raylib.
pause
exit /b 1
)

echo [INFO] Extracting Raylib...

powershell -Command "Expand-Archive raylib.zip -DestinationPath raylib_temp"

echo [INFO] Installing Raylib...

copy "raylib_temp\raylib-5.0_win64_mingw-w64\lib\libraylib.a" "..\lib\" >nul
copy "raylib_temp\raylib-5.0_win64_mingw-w64\include\raylib.h" "..\include\" >nul
copy "raylib_temp\raylib-5.0_win64_mingw-w64\include\raymath.h" "..\include\" >nul
copy "raylib_temp\raylib-5.0_win64_mingw-w64\include\rlgl.h" "..\include\" >nul

rmdir /s /q raylib_temp
del raylib.zip

)

:: Final check
if not exist "%RAYLIB_LIB%" (
echo.
echo [ERROR] Raylib installation failed.
echo Please install manually.
pause
exit /b 1
)

echo [SUCCESS] Raylib ready.

:: ===================================================
:: METADATA WIZARD
:: ===================================================

set /p update_meta="Do you want to edit Game Details? [y/n]: "

if /i "%update_meta%"=="y" (

echo.

set /p g_name="Enter Game Name: "
set "g_name=!g_name: =_!"
set "PROJECT_NAME=!g_name!"

set /p g_desc="Enter Game Description: "
set /p g_comp="Enter Company Name: "
set /p g_vers="Enter Version (e.g. 1.0.0.0): "

echo [SSOEngine] Updating resource.rc...

(
echo // AUTO GENERATED BY SSOENGINE
echo IDI_ICON1 ICON DISCARDABLE "app_icon.ico"
echo.
echo 1 VERSIONINFO
echo FILEVERSION 1,0,0,0
echo PRODUCTVERSION 1,0,0,0
echo BEGIN
echo BLOCK "StringFileInfo"
echo BEGIN
echo BLOCK "040904b0"
echo BEGIN
echo VALUE "CompanyName", "!g_comp!"
echo VALUE "FileDescription", "!g_desc!"
echo VALUE "FileVersion", "!g_vers!"
echo VALUE "InternalName", "!g_name!"
echo VALUE "OriginalFilename", "!g_name!.exe"
echo VALUE "ProductName", "!g_name!"
echo VALUE "ProductVersion", "!g_vers!"
echo END
echo END
echo END
) > %ICON_RES%

echo [SUCCESS] Metadata saved.

)

:: ===================================================
:: BUILD DIRECTORY
:: ===================================================

if not exist "%BUILD_DIR%" mkdir "%BUILD_DIR%"

set "OUTPUT_EXE=%BUILD_DIR%\%PROJECT_NAME%.exe"

:: ===================================================
:: BUILD TOOLS (SSO PACKER)
:: ===================================================

if exist "%ASSET_SRC%" (

echo.
echo [INFO] Checking Build Tools...

pushd ..\00_BuildTools

if not exist "sso_packer.exe" (

echo [INFO] Compiling SSO Asset Packer...

g++ sso_packer.cpp -o sso_packer.exe -std=c++17

if !errorlevel! neq 0 (
echo [ERROR] Failed to compile sso_packer.
popd
pause
exit /b 1
)

echo [SUCCESS] SSO Packer compiled.

)

echo.
echo ==========================================
echo    SSOEngine Asset Packer
echo ==========================================

sso_packer.exe

popd

)

:: ===================================================
:: RESOURCE COMPILATION
:: ===================================================

echo.
echo [INFO] Compiling resources...

if exist "%ICON_RES%" (
windres "%ICON_RES%" -o "%BUILD_DIR%\resource.o"
)

:: ===================================================
:: GAME COMPILATION
:: ===================================================

echo.
echo [INFO] Compiling game...

g++ main.cpp "%BUILD_DIR%\resource.o" -o "%OUTPUT_EXE%" ^
-I. ^
-I../include ^
-L../lib ^
-lraylib ^
-lopengl32 ^
-lgdi32 ^
-lwinmm

:: ===================================================
:: RESULT
:: ===================================================

if %errorlevel% neq 0 (

echo.
echo [ERROR] Build Failed
echo.

echo Troubleshooting:
echo 1. Ensure MinGW-w64 is installed
echo 2. Ensure raylib installed correctly
echo 3. Verify code syntax

pause
exit /b %errorlevel%

)

echo.
echo ===================================================
echo BUILD SUCCESS
echo EXE: %OUTPUT_EXE%
echo ===================================================

pause